
k-make-check:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  variables:
    GIT_STRATEGY: clone
  script:
    - ./ci/k-make-check-wrapper.sh
  after_script:
    - scp -q fun3d@k:/hpnobackup1/fun3d/yoga-ci/${CI_JOB_NAME}-${CI_JOB_ID}/log-\* . || true
  artifacts:
    paths:
      - "log-*"
    when: always
    expire_in: 1 week

