#!/usr/bin/env bash

set -e # exit on first error
set -u # Treat unset variables as error

# Required empty directory not created by git
if test ! -d config
then
  mkdir -p config
fi

if test X"`uname -s`" = X"Darwin"
then
  if test X != X"`which glibtoolize`" -a -e `which glibtoolize`
  then
    libtoolize="glibtoolize"
  else
    libtoolize="libtoolize"
  fi
else
  libtoolize="libtoolize"
fi

aclocal_flags="${ACLOCAL_FLAGS:-}"

echo "Bootstrapping `basename $PWD`..."
$libtoolize --force --copy \
&& aclocal --force -I config ${aclocal_flags} \
&& autoheader --force \
&& automake --gnu --add-missing --copy \
&& autoconf --force \
|| (echo "Failure" && exit 1)

echo "Success"
