if (CMAKE_C_COMPILER_ID STREQUAL "Clang" OR CMAKE_C_COMPILER_ID STREQUAL "AppleClang" OR CMAKE_C_COMPILER_ID STREQUAL "GNU")
    set(CMAKE_C_FLAGS_ASAN "-g -O1 -fno-omit-frame-pointer -fsanitize=address" CACHE STRING "" FORCE)
    set(CMAKE_C_FLAGS_TSAN "-g -O1 -fsanitize=thread" CACHE STRING "" FORCE)
endif()
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(CMAKE_CXX_FLAGS_ASAN "-g -O1 -fno-omit-frame-pointer -fsanitize=address" CACHE STRING "" FORCE)
    set(CMAKE_CXX_FLAGS_TSAN "-g -O1 -fsanitize=thread" CACHE STRING "" FORCE)
endif()
if (CMAKE_Fortran_COMPILER_ID STREQUAL "Clang" OR CMAKE_Fortran_COMPILER_ID STREQUAL "AppleClang" OR CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")
    set(CMAKE_Fortran_FLAGS_ASAN "-g -O1 -fno-omit-frame-pointer -fsanitize=address" CACHE STRING "" FORCE)
    set(CMAKE_Fortran_FLAGS_TSAN "-g -O1 -fsanitize=thread" CACHE STRING "" FORCE)
endif()
